"""initial schema

Revision ID: d3ca5ed3d18d
Revises: 
Create Date: 2026-09-07 13:26:33.139164

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ca5ed3d18d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('geolocation', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('accessibility_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_preferences_user_id'), 'accessibility_preferences', ['user_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_uuid'), 'sessions', ['session_uuid'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobility', sa.String(length=32), nullable=True),
    sa.Column('vision', sa.String(length=32), nullable=True),
    sa.Column('hearing', sa.String(length=32), nullable=True),
    sa.Column('guidance_style', sa.String(length=32), nullable=True),
    sa.Column('walking_speed_mps', sa.Float(), nullable=True),
    sa.Column('max_comfortable_distance_m', sa.Integer(), nullable=True),
    sa.Column('cognitive_load_preference', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_events_event_type'), 'navigation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_navigation_events_session_id'), 'navigation_events', ['session_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_node_type'), 'nodes', ['node_type'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_observations_session_id'), 'scene_observations', ['session_id'], unique=False)
    op.create_table('accessibility_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.String(length=32), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('estimated_distance_m', sa.Float(), nullable=True),
    sa.Column('distance_confidence', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['scene_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_objects_object_type'), 'detected_objects', ['object_type'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('temporary_blockage', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(length=512), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('route_step_id', sa.Integer(), nullable=True),
    sa.Column('expected_action', sa.String(length=256), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('replanned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_step_id'], ['route_steps.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_events')
    op.drop_table('route_steps')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_detected_objects_object_type'), table_name='detected_objects')
    op.drop_table('detected_objects')
    op.drop_table('accessibility_features')
    op.drop_index(op.f('ix_scene_observations_session_id'), table_name='scene_observations')
    op.drop_table('scene_observations')
    op.drop_table('routes')
    op.drop_index(op.f('ix_nodes_node_type'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_navigation_events_session_id'), table_name='navigation_events')
    op.drop_index(op.f('ix_navigation_events_event_type'), table_name='navigation_events')
    op.drop_table('navigation_events')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sessions_session_uuid'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('floors')
    op.drop_index(op.f('ix_accessibility_preferences_user_id'), table_name='accessibility_preferences')
    op.drop_table('accessibility_preferences')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###